<?php

namespace Database\Seeders;

use App\Enums\User\RoleEnum;
use App\Models\Address;
use App\Models\Nanny;
use App\Models\User;
use Illuminate\Database\Seeder;

class NannySeeder extends Seeder
{
    public function run(): void
    {
        $nannyRole = RoleEnum::NANNY->value;

        // Lista de NANNIES
        $candidatas = [
            // GUADALAJARA (44000 - 44999)
            ['name' => 'Mariana', 'surnames' => 'García López', 'email' => 'mariana.garcia@gmail.com', 'number' => '+52 55 1234 5601', 'bio' => 'Estudiante de pedagogía con 3 años cuidando niños de 3 a 7 años. Le encantan las actividades didácticas y leer cuentos.', 'availability' => true, 'start_date' => '2024-08-15', 'postal_code' => '44100', 'street' => 'Av. Juárez #120', 'neighborhood' => 'Centro', 'other_type' => null, 'internal_number' => '2A'],
            ['name' => 'Ximena', 'surnames' => 'Torres Navarro', 'email' => 'ximena.torres@gmail.com', 'number' => '+52 55 7744 8899', 'bio' => 'Apasionada por el desarrollo infantil. Experiencia con hermanitos y gemelos.', 'availability' => true, 'start_date' => '2024-07-20', 'postal_code' => '44280', 'street' => 'Calle Hidalgo #456', 'neighborhood' => 'Santa Tere', 'other_type' => null, 'internal_number' => '3B'],
            ['name' => 'Paola', 'surnames' => 'Sánchez Rivera', 'email' => 'paola.sanchez@outlook.com', 'number' => '+52 33 6677 5588', 'bio' => 'Estudiante de enfermería. Muy organizada con horarios y alimentación.', 'availability' => true, 'start_date' => '2024-11-05', 'postal_code' => '44700', 'street' => 'Calle 8 de Julio #900', 'neighborhood' => 'Oblatos', 'other_type' => null, 'internal_number' => null],
            ['name' => 'Sofía', 'surnames' => 'Díaz Castro', 'email' => 'sofia.diazcastro@gmail.com', 'number' => '+52 33 1122 3344', 'bio' => 'Experiencia en el cuidado de niños en edad escolar. Habilidad para asistir con tareas escolares y promover hábitos de lectura.', 'availability' => true, 'start_date' => '2024-09-10', 'postal_code' => '44720', 'street' => 'Calle Balcones #30', 'neighborhood' => 'Balcones de Oblatos', 'other_type' => 'Guadalajara', 'internal_number' => null],
            ['name' => 'Renata', 'surnames' => 'Pérez Chávez', 'email' => 'renata.pc.gdl@hotmail.com', 'number' => '+52 33 2288 1199', 'bio' => 'Cariñosa y creativa, con experiencia en cuidado nocturno y apoyo con la transición a dormir. Enfoque en el juego simbólico.', 'availability' => true, 'start_date' => '2024-12-05', 'postal_code' => '44670', 'street' => 'Calle Manuel Acuña #150', 'neighborhood' => 'Providencia', 'other_type' => 'Guadalajara', 'internal_number' => '4'],
            ['name' => 'Carolina', 'surnames' => 'Guzmán Ríos', 'email' => 'caroguzman.rios@outlook.com', 'number' => '+52 33 4455 6677', 'bio' => 'Certificada en manejo de situaciones de emergencia. Experiencia en el cuidado de niños con TDAH. Fomenta el deporte.', 'availability' => true, 'start_date' => '2024-11-20', 'postal_code' => '44820', 'street' => 'Calle Esteban Alatorre #75', 'neighborhood' => 'San Onofre', 'other_type' => 'Guadalajara', 'internal_number' => null],
            ['name' => 'Fátima', 'surnames' => 'Trujillo Soto', 'email' => 'fatima_ts_mx@live.com', 'number' => '+52 33 7766 5544', 'bio' => 'Experiencia en el apoyo a padres que trabajan desde casa. Mantiene a los niños entretenidos con bajo ruido y orden.', 'availability' => true, 'start_date' => '2025-02-01', 'postal_code' => '44940', 'street' => 'Av. Cruz del Sur #1500', 'neighborhood' => 'Jardines de la Cruz', 'other_type' => 'Guadalajara', 'internal_number' => '5D'],
            ['name' => 'Alma', 'surnames' => 'Godínez Rocha', 'email' => 'alma.grocha@yahoo.com', 'number' => '+52 33 3030 4040', 'bio' => 'Se especializa en el cuidado de bebés (0-2 años). Habilidad para calmar y establecer horarios de alimentación y sueño.', 'availability' => true, 'start_date' => '2025-01-01', 'postal_code' => '44680', 'street' => 'Calle Rubén Darío #800', 'neighborhood' => 'Jardines de la Patria', 'other_type' => 'Guadalajara', 'internal_number' => '5A'],
            ['name' => 'Marcela', 'surnames' => 'Castro Luna', 'email' => 'marce.cluna@outlook.com', 'number' => '+52 33 7070 8080', 'bio' => 'Experiencia con grupos de varios niños. Organizada, puntual y con enfoque en la seguridad en el hogar.', 'availability' => true, 'start_date' => '2024-12-01', 'postal_code' => '44290', 'street' => 'Calle Eulogio Parra #400', 'neighborhood' => 'Lomas del Country', 'other_type' => 'Guadalajara', 'internal_number' => null],
            ['name' => 'Susana', 'surnames' => 'Ramírez Ortiz', 'email' => 'susi.ramirez.o@hotmail.com', 'number' => '+52 33 9135 7246', 'bio' => 'Apoya en excursiones y paseos al parque. Fomenta la exploración segura del entorno y la socialización.', 'availability' => true, 'start_date' => '2024-12-10', 'postal_code' => '44320', 'street' => 'Calle Belisario Domínguez #1230', 'neighborhood' => 'Huentitán el Bajo', 'other_type' => 'Guadalajara', 'internal_number' => 'C'],
            ['name' => 'Diana', 'surnames' => 'Luna Morales', 'email' => 'diana.luna.m@live.com', 'number' => '+52 33 4987 6543', 'bio' => 'Le encantan las actividades de teatro en casa y juegos de roles. Enfocada en la expresión oral y la confianza.', 'availability' => true, 'start_date' => '2024-10-20', 'postal_code' => '44860', 'street' => 'Calle Josefa Ortiz de Domínguez #780', 'neighborhood' => 'La Penal', 'other_type' => 'Guadalajara', 'internal_number' => '2'],
            ['name' => 'Cecilia', 'surnames' => 'Rojas Chávez', 'email' => 'ceci_rojas.ch@hotmail.com', 'number' => '+52 33 5599 0011', 'bio' => 'Responsable con el seguimiento de medicamentos y alergias. Enfocada en la higiene y el orden en el área de juegos.', 'availability' => true, 'start_date' => '2025-01-01', 'postal_code' => '44130', 'street' => 'Calle Libertad #101', 'neighborhood' => 'Lafayette', 'other_type' => 'Guadalajara', 'internal_number' => null],
            ['name' => 'Nancy', 'surnames' => 'Quiroz Flores', 'email' => 'nancy.qf.gdl@hotmail.com', 'number' => '+52 33 1155 2266', 'bio' => 'Estudiante de psicología infantil. Experiencia en manejo de transiciones y rutinas post-escolares.', 'availability' => true, 'start_date' => '2025-03-01', 'postal_code' => '44607', 'street' => 'Av. Adolfo López Mateos Nte #30', 'neighborhood' => 'Circunvalación Vallarta', 'other_type' => 'Guadalajara', 'internal_number' => '10B'],
            ['name' => 'Victoria', 'surnames' => 'López Castro', 'email' => 'vicky.lopezc@outlook.com', 'number' => '+52 33 4411 5522', 'bio' => 'Experiencia con el cuidado de niños con TDAH. Aplica técnicas de relajación y concentración durante el estudio.', 'availability' => true, 'start_date' => '2025-01-20', 'postal_code' => '44950', 'street' => 'Calle 10 #250', 'neighborhood' => 'Zona Industrial', 'other_type' => 'Guadalajara', 'internal_number' => '4D'],
            ['name' => 'Natalia', 'surnames' => 'Castañeda Ríos', 'email' => 'natalia.castaneda@outlook.com', 'number' => '+52 33 7799 8811', 'bio' => 'Estudiante de nutrición. Experiencia con la preparación de alimentos saludables y divertidos para niños de todas las edades.', 'availability' => true, 'start_date' => '2025-02-10', 'postal_code' => '44689', 'street' => 'Av. México #2000', 'neighborhood' => 'Ladrón de Guevara', 'other_type' => 'Guadalajara', 'internal_number' => '3A'],
            ['name' => 'Rosa', 'surnames' => 'López Chávez', 'email' => 'rosalopezch@gmail.com', 'number' => '+52 33 1144 2255', 'bio' => 'Bilingüe (Español/Francés). Usa el idioma francés en juegos y canciones para niños pequeños que deseen iniciar el aprendizaje.', 'availability' => true, 'start_date' => '2025-01-01', 'postal_code' => '44101', 'street' => 'Calle Pedro Moreno #10', 'neighborhood' => 'Americana', 'other_type' => 'Guadalajara', 'internal_number' => '1C'],
            ['name' => 'Hanna', 'surnames' => 'Vega Larios', 'email' => 'hannavegalarios@gmail.com', 'number' => '+52 33 7700 8811', 'bio' => 'Cuidado de niños con alergias severas. Muy rigurosa con la limpieza y la manipulación de alimentos para prevenir riesgos.', 'availability' => true, 'start_date' => '2025-03-10', 'postal_code' => '44210', 'street' => 'Calle San Jorge #100', 'neighborhood' => 'Santa Cecilia', 'other_type' => 'Guadalajara', 'internal_number' => null],
            ['name' => 'Silvana', 'surnames' => 'Torres Ríos', 'email' => 'silvana_tr@yahoo.com', 'number' => '+52 33 1020 3040', 'bio' => 'Estudiante de enfermería. Muy detallista con la administración de medicamentos y chequeos de salud básicos.', 'availability' => true, 'start_date' => '2025-02-01', 'postal_code' => '44360', 'street' => 'Calle Montes Urales #50', 'neighborhood' => 'Colonia Independencia', 'other_type' => 'Guadalajara', 'internal_number' => '10'],
            ['name' => 'Gabriela', 'surnames' => 'Sánchez Díaz', 'email' => 'gabriela_sdiaz@gmail.com', 'number' => '+52 33 3456 7890', 'bio' => 'Gran paciencia con el entrenamiento para ir al baño. Muy positiva y motivadora en el proceso de dejar el pañal.', 'availability' => true, 'start_date' => '2024-11-01', 'postal_code' => '44690', 'street' => 'Calle Manuel M. Diéguez #5', 'neighborhood' => 'Terranova', 'other_type' => 'Guadalajara', 'internal_number' => 'PB'],
            ['name' => 'Estefanía', 'surnames' => 'Ramos Larios', 'email' => 'estefania.ramos.l@hotmail.com', 'number' => '+52 33 7700 9922', 'bio' => 'Cuidado de apoyo para familias con horarios variables. Muy organizada con el manejo de diferentes horarios de siesta.', 'availability' => true, 'start_date' => '2024-09-01', 'postal_code' => '44250', 'street' => 'Calle Circunvalación #10', 'neighborhood' => 'San Bernardo', 'other_type' => 'Guadalajara', 'internal_number' => '6'],
            ['name' => 'Marisol', 'surnames' => 'Vargas Gómez', 'email' => 'marisolvg@hotmail.com', 'number' => '+52 33 1188 2277', 'bio' => 'Cocinera aficionada, disfruta preparando snacks saludables con los niños. Experiencia con niños de 4 a 8 años.', 'availability' => true, 'start_date' => '2025-03-01', 'postal_code' => '44900', 'street' => 'Calle 5 de Febrero #300', 'neighborhood' => 'Moderna', 'other_type' => 'Guadalajara', 'internal_number' => 'PB'],
            ['name' => 'Susana', 'surnames' => 'Navarro Ríos', 'email' => 'susanariostez@yahoo.com', 'number' => '+52 33 8982 9922', 'bio' => 'Experiencia en cuidado de niños con alergias y necesidades dietéticas especiales (celiaquía). Muy detallista y organizada.', 'availability' => true, 'start_date' => '2024-10-05', 'postal_code' => '44695', 'street' => 'Calle Nelson #10', 'neighborhood' => 'Prados Providencia', 'other_type' => 'Guadalajara', 'internal_number' => '1'],

            // ZAPOPAN (45000 - 45245)
            ['name' => 'Daniela', 'surnames' => 'Hernández Ramírez', 'email' => 'daniela.hernandez@outlook.com', 'number' => '+52 33 9876 5412', 'bio' => 'Niñera certificada en primeros auxilios. Experiencia con bebés y rutinas de sueño.', 'availability' => true, 'start_date' => '2024-09-01', 'postal_code' => '45010', 'street' => 'Calle San Juan #45', 'neighborhood' => 'Zapopan Centro', 'other_type' => null, 'internal_number' => '1'],
            ['name' => 'Fernanda', 'surnames' => 'Martínez Cruz', 'email' => 'fernanda.martinez@hotmail.com', 'number' => '+52 81 2200 3344', 'bio' => 'Apoya a sus hermanitos en sus tiempos libres. Disfruta actividades artísticas y música para estimular el aprendizaje.', 'availability' => true, 'start_date' => '2024-10-10', 'postal_code' => '45190', 'street' => 'Av. Patria #500', 'neighborhood' => 'Puerta de Hierro', 'other_type' => null, 'internal_number' => null],
            ['name' => 'Andrea', 'surnames' => 'Mora Soto', 'email' => 'andrea.mora@outlook.com', 'number' => '+52 33 7788 9900', 'bio' => 'Cuidadora con energía, le gusta organizar juegos didácticos y tiene experiencia manejando alergias alimentarias.', 'availability' => true, 'start_date' => '2024-07-25', 'postal_code' => '45014', 'street' => 'Avenida Guadalupe #201', 'neighborhood' => 'Ciudad del Sol', 'other_type' => 'Zapopan', 'internal_number' => 'PB'],
            ['name' => 'Lucía', 'surnames' => 'Vargas Cruz', 'email' => 'lucia.vcruz@live.com', 'number' => '+52 33 6655 4433', 'bio' => 'Habilidad para manejar rutinas de varios niños a la vez. Fomenta la actividad física con juegos seguros y divertidos.', 'availability' => true, 'start_date' => '2024-11-15', 'postal_code' => '45030', 'street' => 'Avenida Mariano Otero #400', 'neighborhood' => 'Jardines del Sol', 'other_type' => 'Zapopan', 'internal_number' => '10A'],
            ['name' => 'Elisa', 'surnames' => 'Montes López', 'email' => 'elisa.montes78@yahoo.com', 'number' => '+52 33 9900 1122', 'bio' => 'Niñera bilingüe (español/inglés). Le gusta integrar el idioma a través de canciones y cuentos durante el cuidado.', 'availability' => true, 'start_date' => '2025-01-10', 'postal_code' => '45050', 'street' => 'Av. Tepeyac #330', 'neighborhood' => 'Chapalita', 'other_type' => 'Zapopan', 'internal_number' => '1'],
            ['name' => 'Jimena', 'surnames' => 'Herrera Sáenz', 'email' => 'jime.hsaenz@gmail.com', 'number' => '+52 33 8877 6655', 'bio' => 'Apasionada por la cocina básica y nutrición infantil. Prepara meriendas divertidas y saludables, siempre con alegría.', 'availability' => true, 'start_date' => '2024-12-15', 'postal_code' => '45134', 'street' => 'Calle Tulipanes #50', 'neighborhood' => 'Las Lomas', 'other_type' => 'Zapopan', 'internal_number' => 'A'],
            ['name' => 'Elsa', 'surnames' => 'Torres Ruiz', 'email' => 'elsa.truiz.mex@gmail.com', 'number' => '+52 33 5050 6060', 'bio' => 'Excelente motivadora para las tareas escolares. Manejo de actividades lúdicas y juegos de mesa educativos.', 'availability' => true, 'start_date' => '2024-11-10', 'postal_code' => '45070', 'street' => 'Av. Cruz del Sur #15', 'neighborhood' => 'Residencial Victoria', 'other_type' => 'Zapopan', 'internal_number' => '4B'],
            ['name' => 'Silvia', 'surnames' => 'Ibarra Vega', 'email' => 's.ibarra.vega@hotmail.com', 'number' => '+52 33 9090 1010', 'bio' => 'Apasionada por la música y el movimiento. Incorpora baile y juegos rítmicos para el desarrollo motor.', 'availability' => true, 'start_date' => '2025-01-25', 'postal_code' => '45110', 'street' => 'Av. Patria #99', 'neighborhood' => 'Jardines del Valle', 'other_type' => 'Zapopan', 'internal_number' => 'PH'],
            ['name' => 'Laura', 'surnames' => 'Ibarra Gómez', 'email' => 'laura_igo@outlook.com', 'number' => '+52 33 8642 9753', 'bio' => 'Técnica en puericultura. Cuidadosa con la nutrición y el seguimiento de dietas especiales. Prefiere el cuidado de tiempo completo.', 'availability' => true, 'start_date' => '2024-11-01', 'postal_code' => '45080', 'street' => 'Av. Topacio #45', 'neighborhood' => 'Residencial Plaza Guadalupe', 'other_type' => 'Zapopan', 'internal_number' => '10'],
            ['name' => 'Beatriz', 'surnames' => 'Vázquez Bravo', 'email' => 'beavazquezbravo@yahoo.com', 'number' => '+52 33 7000 8111', 'bio' => 'Experiencia con el cuidado de lactantes y manejo de alimentación complementaria (BLW). Muy paciente y atenta.', 'availability' => true, 'start_date' => '2025-02-15', 'postal_code' => '45222', 'street' => 'Paseo de las Bugambilias #50', 'neighborhood' => 'Bugambilias', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Erika', 'surnames' => 'Serrano Vega', 'email' => 'erika_serranovega@gmail.com', 'number' => '+52 33 1199 2288', 'bio' => 'Experiencia cuidando niños con necesidades especiales (TEA leve). Crea ambientes tranquilos y estructurados.', 'availability' => true, 'start_date' => '2024-11-25', 'postal_code' => '45150', 'street' => 'Av. Juan Gil Preciado #100', 'neighborhood' => 'La Cima', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Hilda', 'surnames' => 'Zúñiga Orozco', 'email' => 'hilda.z.orozco@yahoo.com', 'number' => '+52 33 6688 7799', 'bio' => 'Apoyo en el desarrollo del lenguaje. Cuidado muy tranquilo y enfocado en la música clásica para bebés y niños pequeños.', 'availability' => true, 'start_date' => '2024-12-01', 'postal_code' => '45069', 'street' => 'Calle Puerto Guaymas #78', 'neighborhood' => 'Colonia Miramar', 'other_type' => 'Zapopan', 'internal_number' => 'B3'],
            ['name' => 'Yolanda', 'surnames' => 'Salazar Cruz', 'email' => 'yolanda_scruz@gmail.com', 'number' => '+52 33 6677 8899', 'bio' => 'Profesora jubilada. Cuidado cariñoso, basado en la disciplina positiva y el refuerzo de valores.', 'availability' => true, 'start_date' => '2024-09-15', 'postal_code' => '45019', 'street' => 'Av. Patria #10', 'neighborhood' => 'Jardines del Bosque', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Sofía', 'surnames' => 'Ramos Torres', 'email' => 'sofia_rtorres@yahoo.com', 'number' => '+52 33 8811 9922', 'bio' => 'Niñera con habilidades en costura y manualidades. Organiza talleres creativos y juegos de desarrollo de motricidad fina.', 'availability' => true, 'start_date' => '2024-07-20', 'postal_code' => '45130', 'street' => 'Calle Sagitario #50', 'neighborhood' => 'La Calma', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Luz', 'surnames' => 'Mora Ríos', 'email' => 'luz.mora.rios@hotmail.com', 'number' => '+52 33 3366 4477', 'bio' => 'Trabajó en kínder por 2 años. Excelente manejo de grupos y autoridad positiva. Enfocada en el desarrollo social.', 'availability' => true, 'start_date' => '2024-08-15', 'postal_code' => '45010', 'street' => 'Av. La Paz #200', 'neighborhood' => 'Vallarta Poniente', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Elena', 'surnames' => 'Díaz Rangel', 'email' => 'elena.drangel@yahoo.com', 'number' => '+52 33 9911 0022', 'bio' => 'Experiencia con el cuidado de infantes de menos de un año. Maneja técnicas de masaje infantil y estimulación sensorial.', 'availability' => true, 'start_date' => '2024-10-01', 'postal_code' => '45138', 'street' => 'Av. Acueducto #300', 'neighborhood' => 'Solares', 'other_type' => 'Zapopan', 'internal_number' => '4'],
            ['name' => 'Alejandra', 'surnames' => 'Ortega Mora', 'email' => 'ale.ortega.mora@gmail.com', 'number' => '+52 33 5533 6644', 'bio' => 'Entrenamiento en primeros auxilios avanzado. Enfocada en la seguridad, especialmente en niños pequeños y bebés.', 'availability' => true, 'start_date' => '2024-09-01', 'postal_code' => '45136', 'street' => 'Calle Pino #15', 'neighborhood' => 'Tierra Blanca', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Sandra', 'surnames' => 'Rico Solís', 'email' => 'sandy.rico@yahoo.com', 'number' => '+52 33 2277 3388', 'bio' => 'Niñera con experiencia en cuidado de varios años y manejo de fines de semana. Fomenta el juego libre y la imaginación.', 'availability' => true, 'start_date' => '2024-11-01', 'postal_code' => '45088', 'street' => 'Calle Obsidiana #20', 'neighborhood' => 'El Palomar', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Jessica', 'surnames' => 'Godínez Mora', 'email' => 'jessica.gmora@live.com', 'number' => '+52 33 5060 7080', 'bio' => 'Apasionada por la lectura y la biblioteca. Organiza sesiones de lectura en voz alta para fomentar el amor por los libros.', 'availability' => true, 'start_date' => '2024-08-01', 'postal_code' => '45130', 'street' => 'Calle Patria #88', 'neighborhood' => 'Jardines de Guadalupe', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Pamela', 'surnames' => 'Cortés Vargas', 'email' => 'pamelacortesv@yahoo.com', 'number' => '+52 33 1133 5577', 'bio' => 'Certificada en nutrición infantil. Puede preparar comidas completas siguiendo recetas saludables y orgánicas.', 'availability' => true, 'start_date' => '2024-10-10', 'postal_code' => '45110', 'street' => 'Calle Paseo de las Palmas #30', 'neighborhood' => 'Jardines del Valle', 'other_type' => 'Zapopan', 'internal_number' => '22'],
            ['name' => 'Paulina', 'surnames' => 'Vargas Pérez', 'email' => 'paulina_vperez@outlook.com', 'number' => '+52 33 4466 8800', 'bio' => 'Especializada en actividades STEM sencillas (ciencia, tecnología, ingeniería, matemáticas) para niños preescolares.', 'availability' => true, 'start_date' => '2025-01-15', 'postal_code' => '45040', 'street' => 'Av. de las Américas #55', 'neighborhood' => 'Minerva', 'other_type' => 'Zapopan', 'internal_number' => null],
            ['name' => 'Samantha', 'surnames' => 'Cruz Mota', 'email' => 'samantha_cruzm@live.com', 'number' => '+52 33 3355 7799', 'bio' => 'Estudiante de danza. Fomenta el movimiento corporal y la expresión creativa a través de juegos rítmicos.', 'availability' => true, 'start_date' => '2025-02-01', 'postal_code' => '45030', 'street' => 'Calle Cubilete #40', 'neighborhood' => 'Jardines del Sol', 'other_type' => 'Zapopan', 'internal_number' => '1B'],
            ['name' => 'Viviana', 'surnames' => 'Díaz Rangel', 'email' => 'viviana.drangel@outlook.com', 'number' => '+52 33 5599 8939', 'bio' => 'Certificada en desarrollo de lenguaje temprano. Utiliza tarjetas y rimas para estimular la comunicación en bebés y toddlers.', 'availability' => true, 'start_date' => '2024-11-20', 'postal_code' => '45119', 'street' => 'Av. Universidad #15', 'neighborhood' => 'Santa Margarita', 'other_type' => 'Zapopan', 'internal_number' => '12A'],

            // TLAJOMULCO (45640 - 45679)
            ['name' => 'Valeria', 'surnames' => 'Ramos Torres', 'email' => 'valeria.rt@hotmail.com', 'number' => '+52 33 5544 3322', 'bio' => 'Gran paciencia con niños pequeños, especializada en juegos al aire libre y en actividades que fomentan la creatividad.', 'availability' => true, 'start_date' => '2024-08-01', 'postal_code' => '45643', 'street' => 'Avenida de Los Gavilanes #150', 'neighborhood' => 'Los Gavilanes', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => '4C'],
            ['name' => 'Rebeca', 'surnames' => 'Núñez Pérez', 'email' => 'rebeca.nunez@yahoo.com', 'number' => '+52 33 2211 5566', 'bio' => 'Apasionada por el teatro y la narración de cuentos. Cuidado cariñoso con foco en el bienestar emocional de los niños.', 'availability' => true, 'start_date' => '2024-10-01', 'postal_code' => '45654', 'street' => 'Calle Benito Juárez #88', 'neighborhood' => 'San Agustín', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => null],
            ['name' => 'Verónica', 'surnames' => 'Márquez Soto', 'email' => 'vero_marquez_soto@live.com', 'number' => '+52 33 1001 2002', 'bio' => 'Cuidadora de apoyo para fines de semana. Fomenta el respeto por los animales y actividades de reciclaje.', 'availability' => true, 'start_date' => '2024-12-20', 'postal_code' => '45660', 'street' => 'Calle San Francisco #25', 'neighborhood' => 'Santa Anita', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => null],
            ['name' => 'Abril', 'surnames' => 'Santos Ponce', 'email' => 'abril.santosponce@outlook.com', 'number' => '+52 33 3377 4488', 'bio' => 'Joven y dinámica. Le gusta organizar búsquedas del tesoro y juegos de mesa. Disponible para horarios flexibles.', 'availability' => true, 'start_date' => '2024-09-05', 'postal_code' => '45653', 'street' => 'Av. Concepción #5', 'neighborhood' => 'Concepción del Valle', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => 'A1'],
            ['name' => 'Brenda', 'surnames' => 'Mora Larios', 'email' => 'brenda.mlarios@live.com', 'number' => '+52 33 1245 7800', 'bio' => 'Experiencia en el manejo de mascotas en casa (perros). Le gusta fomentar la lectura y la pintura al aire libre.', 'availability' => true, 'start_date' => '2025-02-28', 'postal_code' => '45661', 'street' => 'Av. López Mateos Sur #900', 'neighborhood' => 'Las Terrazas', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => '3'],
            ['name' => 'Giselle', 'surnames' => 'Mendoza Ríos', 'email' => 'giselita.mendoza@gmail.com', 'number' => '+52 33 2468 1357', 'bio' => 'Gran narradora de cuentos. Experiencia con niños de 5 a 10 años, enfocada en la resolución de problemas y lógica.', 'availability' => true, 'start_date' => '2025-01-15', 'postal_code' => '45640', 'street' => 'Calle Santa Cruz #10', 'neighborhood' => 'La Cofradía', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => '7'],
            ['name' => 'Mónica', 'surnames' => 'Zavala Dávalos', 'email' => 'monica_zdavalos@live.com', 'number' => '+52 33 3399 4400', 'bio' => 'Especializada en actividades de arte y música. Crea un ambiente estimulante y alegre para niños de 3 a 6 años.', 'availability' => true, 'start_date' => '2024-10-15', 'postal_code' => '45669', 'street' => 'Av. Bosques de Santa Anita #100', 'neighborhood' => 'Bosques de Santa Anita', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => 'Casa 5'],
            ['name' => 'Julia', 'surnames' => 'Chávez Lira', 'email' => 'juliachavezlira@hotmail.com', 'number' => '+52 33 6655 7788', 'bio' => 'Flexible con horarios nocturnos. Ayuda con la cena ligera y rutinas de higiene antes de dormir.', 'availability' => true, 'start_date' => '2024-12-01', 'postal_code' => '45653', 'street' => 'Calle Las Torres #40', 'neighborhood' => 'Santa Fe', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => '12'],
            ['name' => 'Daniela', 'surnames' => 'Pérez Soto', 'email' => 'daniperezsoto@live.com', 'number' => '+52 33 9922 1133', 'bio' => 'Experiencia con el cuidado de gemelos y hermanos de edades cercanas. Manejo eficiente de múltiples rutinas y actividades.', 'availability' => true, 'start_date' => '2024-10-05', 'postal_code' => '45645', 'street' => 'Calle Los Pinos #1', 'neighborhood' => 'San Sebastianito', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => '2F'],
            ['name' => 'Gloria', 'surnames' => 'Ortiz García', 'email' => 'gloriaortizg@outlook.com', 'number' => '+52 33 5588 6699', 'bio' => 'Apasionada por la jardinería y actividades al aire libre. Fomenta la conexión con la naturaleza en juegos seguros.', 'availability' => true, 'start_date' => '2024-11-20', 'postal_code' => '45657', 'street' => 'Calle Aldama #50', 'neighborhood' => 'Cuexcomatitlán', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => 'B'],
            ['name' => 'Patricia', 'surnames' => 'Godínez Vera', 'email' => 'patricia_gvera@live.com', 'number' => '+52 33 2233 4455', 'bio' => 'Cuidado a domicilio con enfoque en la seguridad digital. Enseña uso responsable y limitado de pantallas.', 'availability' => true, 'start_date' => '2024-12-01', 'postal_code' => '45650', 'street' => 'Calle López Cotilla #5', 'neighborhood' => 'Tlajomulco Centro', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => '7C'],
            ['name' => 'Karla', 'surnames' => 'Márquez Lira', 'email' => 'karla.marquez.lira@hotmail.com', 'number' => '+52 33 8899 0011', 'bio' => 'Experiencia en el traslado seguro de niños (con silla de coche propia). Apoyo para llevar y recoger de actividades extraescolares.', 'availability' => true, 'start_date' => '2024-12-10', 'postal_code' => '45647', 'street' => 'Calle Bugambilias #5', 'neighborhood' => 'Chulavista', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => '1'],
            ['name' => 'Adriana', 'surnames' => 'Pérez Ruiz', 'email' => 'adriana.pruiz.gdl@outlook.com', 'number' => '+52 33 9080 7060', 'bio' => 'Enfoque en el desarrollo psicomotor. Usa juegos de coordinación y equilibrio para el desarrollo físico y cognitivo.', 'availability' => true, 'start_date' => '2025-01-05', 'postal_code' => '45648', 'street' => 'Av. 8 de Julio #100', 'neighborhood' => 'San Agustin', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => '9A'],
            ['name' => 'Irma', 'surnames' => 'Álvarez Soto', 'email' => 'irma_alvarez@live.com', 'number' => '+52 33 2244 6688', 'bio' => 'Experiencia en el cuidado de mascotas grandes (perros, gatos) mientras cuida a los niños. Responsable y atenta.', 'availability' => true, 'start_date' => '2025-03-20', 'postal_code' => '45649', 'street' => 'Calle Lázaro Cárdenas #50', 'neighborhood' => 'El Zapote del Valle', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => null],
            ['name' => 'Irene', 'surnames' => 'Soto Chávez', 'email' => 'irene.sotoc@gmail.com', 'number' => '+52 33 1237 6688', 'bio' => 'Especialista en arte-terapia para niños. Utiliza pintura y modelado para ayudar a los niños a expresar sus emociones.', 'availability' => true, 'start_date' => '2025-01-10', 'postal_code' => '45664', 'street' => 'Av. De Las Fuentes #88', 'neighborhood' => 'Las Fuentes', 'other_type' => 'Tlajomulco de Zúñiga', 'internal_number' => null],

            // TLAQUEPAQUE (45500 - 45639) - *Nuevos CP asignados*
            ['name' => 'Teresa', 'surnames' => 'Núñez Solís', 'email' => 'teresa.nsolis@gmail.com', 'number' => '+52 33 8000 9000', 'bio' => 'Experiencia en el cuidado de niños con autismo. Paciente y fomenta el desarrollo de habilidades sociales.', 'availability' => true, 'start_date' => '2024-09-20', 'postal_code' => '45570', 'street' => 'Calle Matamoros #10', 'neighborhood' => 'Centro de Tlaquepaque', 'other_type' => 'Tlaquepaque', 'internal_number' => 'A'],
            ['name' => 'Jimena', 'surnames' => 'Luna Pérez', 'email' => 'jimena_luna@outlook.com', 'number' => '+52 33 7000 8000', 'bio' => 'Enfoque en el juego sensorial para niños pequeños. Habilidad para crear juguetes y actividades con materiales reciclados.', 'availability' => true, 'start_date' => '2024-11-15', 'postal_code' => '45600', 'street' => 'Av. San Pedro #300', 'neighborhood' => 'San Pedro Tlaquepaque', 'other_type' => 'Tlaquepaque', 'internal_number' => null],

            // TONALÁ (45400 - 45429) - *Nuevos CP asignados*
            ['name' => 'Elena', 'surnames' => 'Pérez Chávez', 'email' => 'elena.perez.ch@gmail.com', 'number' => '+52 33 6000 7000', 'bio' => 'Niñera con flexibilidad de horario. Le gusta la cocina saludable y actividades al aire libre.', 'availability' => true, 'start_date' => '2024-10-01', 'postal_code' => '45403', 'street' => 'Calle Hidalgo #50', 'neighborhood' => 'Puente Grande', 'other_type' => 'Tonalá', 'internal_number' => '5'],
            ['name' => 'Maribel', 'surnames' => 'Ríos Godínez', 'email' => 'maribel.riosg@hotmail.com', 'number' => '+52 33 5000 6000', 'bio' => 'Experiencia en el apoyo a tareas de primaria. Enfocada en la lectura y escritura creativa.', 'availability' => true, 'start_date' => '2024-11-20', 'postal_code' => '45420', 'street' => 'Av. Tonaltecas #200', 'neighborhood' => 'Centro de Tonalá', 'other_type' => 'Tonalá', 'internal_number' => '10'],
        ];

        // =============================
        // Creación de usuarios y nannies
        // =============================
        foreach ($candidatas as $data) {
            // Crear el usuario
            $user = User::factory()->state([
                'name' => $data['name'],
                'surnames' => $data['surnames'],
                'email' => $data['email'],
                'number' => $data['number'],
            ])->create();

            $user->assignRole($nannyRole);

            // Crear la niñera
            $nanny = Nanny::create([
                'user_id' => $user->id,
                'bio' => $data['bio'],
                'availability' => $data['availability'],
                'start_date' => $data['start_date'],
            ]);

            // Crear su dirección asociada (sin type, se genera aleatorio en el factory)
            Address::factory()->state([
                'postal_code' => $data['postal_code'],
                'street' => $data['street'],
                'neighborhood' => $data['neighborhood'],
                'other_type' => $data['other_type'],
                'internal_number' => $data['internal_number'],
            ])->forNanny($nanny)->create();
        }
    }
}
